package fpt.edu.project.model;
// Generated Oct 22, 2020 7:25:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "Color", schema = "dbo", catalog = "YourAnswer")
public class Color implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int colorId;
	private String colorName;
	private Set<ProductColor> productColors = new HashSet<ProductColor>(0);

	public Color() {
	}

	public Color(int colorId) {
		this.colorId = colorId;
	}

	public Color(int colorId, String colorName, Set<ProductColor> productColors) {
		this.colorId = colorId;
		this.colorName = colorName;
		this.productColors = productColors;
	}

	@Id

	@Column(name = "colorId", unique = true, nullable = false)
	public int getColorId() {
		return this.colorId;
	}

	public void setColorId(int colorId) {
		this.colorId = colorId;
	}

	@Column(name = "colorName")
	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<ProductColor> getProductColors() {
		return this.productColors;
	}

	public void setProductColors(Set<ProductColor> productColors) {
		this.productColors = productColors;
	}

}
