package fpt.edu.project.model;
// Generated Oct 22, 2020 7:25:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductColor generated by hbm2java
 */
@Entity
@Table(name = "ProductColor", schema = "dbo", catalog = "YourAnswer")
public class ProductColor implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int productColorId;
	private Color color;
	private Product product;
	private int quantity;
	private Set<CartDetail> cartDetails = new HashSet<CartDetail>(0);

	public ProductColor() {
	}

	public ProductColor(int productColorId, Color color, Product product, int quantity) {
		this.productColorId = productColorId;
		this.color = color;
		this.product = product;
		this.quantity = quantity;
	}

	public ProductColor(int productColorId, Color color, Product product, int quantity, Set<CartDetail> cartDetails) {
		this.productColorId = productColorId;
		this.color = color;
		this.product = product;
		this.quantity = quantity;
		this.cartDetails = cartDetails;
	}

	@Id

	@Column(name = "productColorId", unique = true, nullable = false)
	public int getProductColorId() {
		return this.productColorId;
	}

	public void setProductColorId(int productColorId) {
		this.productColorId = productColorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colorId", nullable = false)
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productColor")
	public Set<CartDetail> getCartDetails() {
		return this.cartDetails;
	}

	public void setCartDetails(Set<CartDetail> cartDetails) {
		this.cartDetails = cartDetails;
	}

}
